# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

variables:
  AZURE_SERVICE_CONNECTION: 'GitHub connection 2' # Name of your Azure Service Connection
  TF_VAR_client_id: $(ARM_CLIENT_ID)
  TF_VAR_client_secret: $(ARM_CLIENT_SECRET)
  TF_VAR_subscription_id: $(ARM_SUBSCRIPTION_ID)
  TF_VAR_tenant_id: $(ARM_TENANT_ID)

steps:
- task: UsePythonVersion@1
  inputs:
    versionSpec: '3.x'

- task: TerraformInstaller@0
  inputs:
    terraformVersion: '1.5.0'

- script: |
    terraform init
  displayName: 'Terraform Init'

- script: |
    terraform plan -out=plan.tfplan
  displayName: 'Terraform Plan'

- script: |
    terraform apply -auto-approve plan.tfplan
  displayName: 'Terraform Apply'

